spring:
  redis:
    host: 192.168.15.67
    port: 6379
    password: welcome123
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 1000
        min-idle: 0
        max-idle: 100
        max-wait: 10000ms