flink:
  mysql:
    host: localhost
    port: 3306
    username: root
    password: 123456
    databases:
      - learning_flink
    tables:
      - learning_flink.t_product_info
      - learning_flink.t_order_bill
      - learning_flink.t_user_info

logging:
  level:
    com:
      collin:
        learning:
          flink: DEBUG

spring:
  redis:
    host: localhost
    port: 6379
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 1000
        min-idle: 0
        max-idle: 100
        max-wait: 10000ms